### PR TITLE
changed SHA256 to SHA512 to match the pulumi publishing

### LINKED ISSUE #11: Winget deploy failed
See: https://github.com/pulumi/pulumi-winget/actions/runs/3056677655/jobs/4931075802

### PR DESCRIPTION
**Pull request by dixler**
Fixes #11 

Is there anything I should update that I haven't updated to fix this?

### CODE REVIEW

File: src/Program.fs [hunk 1]
```diff
@@ -54,10 +54,10 @@ let findWindowsBinaries (release: Release) : Result<InstallerAsset, string> =
                 Error "Could not find the installer SHA256 for the windows build"
```
Comment (dixler) [inline src/Program.fs:54]:
```suggestion
                Error "Could not find the installer SHA512 for the windows build"

```

**Review by Zaid-Ajaj — APPROVED** [review]
